### ISSUE TITLE
"Error: psi values too close each other" with segmented 2.0-1

### ISSUE THREAD

**Issue by benduc** [madsen-lab/valiDrops#14] opened 2024-01-10 13:13 UTC
Hi,
Thanks for developing this great tool.
Since the package **segmented** was updated to 2.0-1, there are several samples that crash when running
```
valiDrops(seurat, rank_barcodes = FALSE)
```
 due to the error "**Error: psi values too close each other. Please change (decreases number of) starting values**".

This is solved when reinstalling segmented 1.6.4.

**Comment by JesperGrud** [comment] 2024-01-15 11:40
Hi.

Thank you for your interest in using valiDrops. That sounds curious. We will try to reproduce with different versions of segmented and get back to you as soon as possible. However, it may be some time. In the mean time I would advise you to use 1.6.4

**Comment by ashipde** [comment] 2024-04-14 21:46
I too encounter this issue, which seems to be solved by reducing _npsi_ to 2 (default is 3). I haven't tried downgrading segmented to 1.6 from the current version, 2.0. I wish the documentation had more information on parameters like npsi and mito.max so one could understand the consequences of changing them from default values.

**Comment by ashipde** [comment] 2024-04-25 01:47
This issue appears to be fixed in v1.1.0.

**Comment by JesperGrud** [comment] 2024-06-17 09:13
Closing as this error is also being evaluated in issue #17

**Closed by JesperGrud** 2024-06-17 09:13 UTC
